#!/bin/bash

# Help String
USAGE="NAME
    mdpdf: For compiling markdown to pdf with mathjax support

USE:
    mdpdf source.md             <- Compile source.md to source.pdf
    mdpdf -h or mdpdf --help    <- prints this string"


if [ $1 = "-h" ]; then
    echo $USAGE
else
    while [[ $# -gt 0 ]]; do
        STEM=${1%.*}
        pandoc -f markdown_github+tex_math_dollars $1 -o $STEM.pdf
        shift
    done
fi
